export const siteConfig = {
  name: "Drone Scope",
  url: "https://dronescope.ro",
  locale: "ro_RO",
  language: "ro",
  title: "Filmări cu Dronă Constanța | Fotografii Aeriene | Drone Scope",
  description:
    "Filmări cu dronă și fotografii aeriene în Constanța, Mamaia, Năvodari și pe tot litoralul. Servicii pentru imobiliare, nunți, evenimente și construcții. Piloți autorizați CAA, echipament DJI, peste 10 ani experiență.",
  shortDescription:
    "Filmări cu dronă și fotografii aeriene profesionale în Constanța și România. Imobiliare, nunți, evenimente și marketing — calitate cinematografică.",
  phone: "+40729626932",
  phoneDisplay: "0729 626 932",
  email: "contact@dronescope.ro",
  address: {
    city: "Constanța",
    region: "Constanța",
    country: "RO",
    countryName: "România",
  },
  geo: {
    latitude: 44.1598,
    longitude: 28.6348,
  },
  social: {
    whatsapp: "https://wa.me/40729626932",
  },
  serviceAreas: [
    "Constanța",
    "Mamaia",
    "Mamaia Nord",
    "Năvodari",
    "Eforie Nord",
    "Eforie Sud",
    "Costinești",
    "Mangalia",
    "Ovidiu",
    "București",
  ],
  ogImage:
    "https://images.pexels.com/photos/1761279/pexels-photo-1761279.jpeg?auto=compress&cs=tinysrgb&w=1200&h=630&fit=crop",
  keywords: [
    "filmări cu dronă",
    "filmare dronă",
    "filmări cu dronă Constanța",
    "fotografii aeriene",
    "filmări aeriene",
    "filmări dronă Mamaia",
    "filmări imobiliare dronă",
    "nunți cu dronă",
    "nuntă cu dronă Constanța",
    "videoclipuri aeriene",
    "video aerian",
    "servicii drone Constanța",
    "fotografii aeriene litoral",
    "filmări industriale dronă",
    "preț filmare dronă",
    "pilot dronă autorizat CAA",
    "filmări evenimente dronă",
    "tur virtual dronă imobiliare",
  ],
  services: [
    "Filmări și fotografii imobiliare cu dronă",
    "Reclame și marketing aerian",
    "Filmări cu dronă pentru nunți și evenimente",
    "Filmări industriale și construcții",
    "Videoclipuri corporate aeriene",
  ],
} as const;