export const siteConfig = {
  name: "Drone Scope",
  url: "https://dronescope.ro",
  locale: "ro_RO",
  language: "ro",
  title: "Filmări cu Dronă Constanța | Fotografii Aeriene | Drone Scope",
  description:
    "Filmări cu dronă în Constanța și pe litoral — imobiliare, nunți, industrial, termal, randare 3D, FPV și 360°. Flotă DJI Matrice 4T, Mavic 4 Pro, Mini 5 Pro, Avata 360. Piloți autorizați CAA, peste 10 ani experiență.",
  shortDescription:
    "Filmări cu dronă profesionale în Constanța: cinematic, termal, randare 3D, FPV și 360°. Matrice 4T, Mavic 4 Pro, Mini 5 Pro, Avata 360.",
  phone: "+40729626932",
  phoneDisplay: "0729 626 932",
  email: "contact@dronescope.ro",
  address: {
    city: "Constanța",
    region: "Constanța",
    country: "RO",
    countryName: "România",
  },
  geo: {
    latitude: 44.1598,
    longitude: 28.6348,
  },
  social: {
    whatsapp: "https://wa.me/40729626932",
  },
  serviceAreas: [
    "Constanța",
    "Mamaia",
    "Mamaia Nord",
    "Năvodari",
    "Eforie Nord",
    "Eforie Sud",
    "Costinești",
    "Mangalia",
    "Ovidiu",
    "București",
  ],
  ogImage:
    "https://images.pexels.com/photos/1761279/pexels-photo-1761279.jpeg?auto=compress&cs=tinysrgb&w=1200&h=630&fit=crop",
  keywords: [
    "filmări cu dronă",
    "filmare dronă",
    "filmări cu dronă Constanța",
    "fotografii aeriene",
    "filmări aeriene",
    "filmări dronă Mamaia",
    "filmări imobiliare dronă",
    "nunți cu dronă",
    "nuntă cu dronă Constanța",
    "videoclipuri aeriene",
    "video aerian",
    "servicii drone Constanța",
    "fotografii aeriene litoral",
    "filmări industriale dronă",
    "preț filmare dronă",
    "pilot dronă autorizat CAA",
    "filmări evenimente dronă",
    "tur virtual dronă imobiliare",
    "inspecții termale dronă",
    "randare 3D dronă",
    "fotogrammetrie dronă",
    "filmări 360 dronă",
    "filmări FPV dronă",
    "DJI Matrice 4T",
  ],
  services: [
    "Filmări și fotografii imobiliare cu dronă",
    "Reclame și marketing aerian",
    "Filmări cu dronă pentru nunți și evenimente",
    "Filmări industriale, termale și randare 3D",
    "Filmări FPV și 360° imersive",
    "Videoclipuri corporate aeriene",
  ],
} as const;